---
variables:
  TERRAFORM_MODULE_NAME: digitalocean-kubernetes
  TERRAFORM_MODULE_SYSTEM: digitalocean
  TF_VAR_admin_ips: '192.168.0.1,192.168.0.2'

include:
  - project: 'grancell/cicd/terraform'
    ref: main
    file:
      - '/module.yaml'
